numpy arrays

In [1]:
my_list = [1,2,3,4,5,6]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)


#we can cast a normal python list into an array or one dimensional array

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

#2 dimensional array / matrix

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#common way in creating numpy array is using numpy.arange([start, ]stop, [step, ]

In [7]:
np.arange(0,1)

array([0])

#now including the third argument [step], I will use 2 because i want to return even numbers from 0-10, it will step by 2

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

#RANDOM

#now lets use some of a few ways to create an arrays of random numbers using this random methods

In [9]:
np.random.rand(5)

array([0.22145162, 0.71063467, 0.90602962, 0.12501002, 0.15384772])

#randn Return a sample (or samples) from the “standard normal” distribution around zero

In [10]:
np.random.randn(2)

array([ 0.4766488 , -0.32754161])

#randint return random numbers from low to high number

In [11]:
np.random.randint(1,10)

9

#other ways and methods. we can use it like example below

In [12]:
from numpy.random import randint

In [13]:
randint(0,30)

7

#lets use some of few attributes and method of an array

In [14]:
arr1 = np.arange(25)

In [15]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
randarray = np.random.randint(0,25,5)
randarray

array([13, 10, 21,  5, 22])

#reshape method - use to return an array into a new shape
#now i want to reshape my array into 5x5

In [17]:
arr1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#finding min and max values method

In [18]:
randarray.max()

22

In [19]:
randarray.min()

5

In [20]:
randarray

array([13, 10, 21,  5, 22])

finding index value of min and max method

In [21]:
randarray.argmax()

4

In [22]:
randarray.argmin()

3

In [23]:
arr1.shape

(25,)

In [24]:
arr1 = arr1.reshape(5,5)

In [25]:
arr1.shape

(5, 5)

#if we want to know the data type of array

In [26]:
arr1.dtype

dtype('int32')

#numpy array indexing and selection

In [27]:
get_arr = np.arange(0,11)

In [28]:
get_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
get_arr[3]

3

#using slice notation
#start = include everything STARTING AT this idx (inclusive)
#stop = include everything BEFORE this idx (exclusive)
#step = (can be ommitted) difference between each idx in the sequence
#a[start:stop] # items start through stop-1
#a[start:] # items start through the rest of the array
#a[:stop] # items from the beginning through stop-1
#a[:] # a copy of the whole array

In [30]:
get_arr[1:5]

array([1, 2, 3, 4])

In [31]:
get_arr[7:]

array([ 7,  8,  9, 10])

In [32]:
get_arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [33]:
get_arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
#copy numpy array

In [35]:
arr_copy = get_arr.copy()

In [36]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#now lets modify get_arr

In [37]:
get_arr[:] = 23

In [38]:
get_arr

array([23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23])

In [39]:
#by modifying get_arr when i broadcast my copy of array every values are unaffected compare to original array

In [40]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#array indexing and selection in 2d arrays

In [41]:
arr_2d = np.array([[2,4,6],[8,10,12],[14,16,18]])

In [42]:
arr_2d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

#for instance i want to grab digit 4
#arr_2d[],[]in first bracket means row that i want and the second bracket is column i want
#so arr_2d[0],[1]will return the value 4

In [43]:
arr_2d[0][1]

4

In [44]:
#now lets grab 18

In [45]:
arr_2d[2][2]

18

#other ways and method to do that is using comma single bracket notation and it works exactly the same

In [46]:
arr_2d[2,2]

18

In [47]:
#slicing notation in 2d array

In [48]:
arr_2d[2:,1:]

array([[16, 18]])

In [49]:
arr_2d[2]

array([14, 16, 18])

In [50]:
arr_2d[:1,1:]

array([[4, 6]])

In [51]:
arr_2d[:2]

array([[ 2,  4,  6],
       [ 8, 10, 12]])

#conditional selection

In [52]:
arr_cs = np.arange(1,11)

In [53]:
bool_arr = arr_cs>3

In [54]:
bool_arr

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

#return bool_arr true value
#it is same as variable inside itself   arr_cs[arr_cs>3]

In [55]:
arr_cs[bool_arr]

array([ 4,  5,  6,  7,  8,  9, 10])

#few excercise slicing notation in 2d array

In [56]:
arr2d = np.arange(60).reshape(6,10)

In [57]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

#lets grab 23, 24, 25, 33, 34, 35,
#firsr break it into [rows:column]
#2:4 use 2 to select the row and 4 to select column
#3:6 to slice the row and column [indexcolumn 3:not including 6]

In [84]:
arr2d[2:4,3:6]


array([[23, 24, 25],
       [33, 34, 35]])

#lets grab 57,58,59

In [75]:
arr2d[5:,7:]

array([[57, 58, 59]])

In [85]:
arr2d[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

#selecting the first 40 index

In [87]:
arr2d[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [88]:
arr2d[0:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])